# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  # github: "#"
  # weibo: "#"
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /images/main.png

#你的头像url
avatar: /images/main.png
#是否开启分享
share_jia: false
share_addthis: false

#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  Lebron James: http://www.nba.hupu.com/
  GitHub: https://github.com/RunnanZhang/
  公孙二狗: http://xtuer.github.io/
  QtBook: http://qtdebug.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 天之道，损有余而补不足，是故虚胜实，不足胜有余。
